# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25b7a36aead14cbdaf084d9ddc9f667d8cf1552b4623456f5e0fe7cb08f9ac578ff2c70343eeedf7a69dd15ebfbcbee66049292c162e87f3cc4d275b84fb4f68

test:
  secret_key_base: 3b91d5c5baf5858efd8435bfe4b25012a98bb97d9b0cbdd07ef706d380bcbef24934c578370af2a3748f6d8bbf3a79f65281c42fdeaa12e34bf01f584299e2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
